<?php


namespace App\Document\Areabrick;


use Pimcore\Model\DataObject\Product;
use Pimcore\Model\Document\Editable\Area\Info;

class Products extends AbstractAreabrick
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'Nos services';
    }

    public function action(Info $info)
    {
        $info->setParams(['products' => Product::getList()->getData()]);
        return parent::action($info); // TODO: Change the autogenerated stub
    }
}
